### PR TITLE
Improve logo

### PR DESCRIPTION
**Pull request by tagliala**
### Some context

Hi, this is a minor thing that could be backported to `main` branch. I was experimering with [Tailwind](https://tailwindcss.com/), and I've found MailCatcher's UI a good place to start. More experiments on [this branch](https://github.com/tagliala/mailcatcher/tree/feature/tailwind) if anyone wants to contribute or keep working on it or even better rewrite with a front-end javascript framework

### This PR

- Fix logo large to be square (124x124)
- Multiple size favicon: 16, 32, and 64px
- HiDPI logo

The HiDPI Sass media query has been generated by autoprefixer with a
">= 0.1%" default

### Before vs After

image

### CODE REVIEW

**Comment by sj26** [comment]
Lovely, thanks! Ready to merge?

**Comment by tagliala** [comment]
> Ready to merge?

Hi, I wanted to check on a non-retina display before

**Comment by Bertg** [comment]
I checked it* on my HD and non HD monitors. Looks good in both situations.

* I recreated the CSS/HTML setup, I did not run the actually branch.

**Comment by sj26** [comment]
Thanks!

**Comment by tagliala** [comment]
Thanks for the test

**Comment by sj26** [comment]
This is shipped in the latest version, v0.8.0.

```
gem install mailcatcher
```

**Comment by tagliala** [comment]
Hi @sj26, thanks for the release

I was experimenting on other UI improvements not related to this PR. I will open a new issue to see if someone is interested in continuing my work or helping me

**Pull request merged**
