### PR TITLE
To, Cc and Bcc feature added

### PR DESCRIPTION
**Pull request by dominh**
Please look at https://github.com/sj26/mailcatcher/issues/17
I'm not sure if it's fully correct but it was useful when I was working with applicationmailer 3.2

### CODE REVIEW

**Comment by taiar** [comment]
I would love to have this feature but I cloned your repo and test your patch and it seems broke.

Web interface is totally wrong here, look:

image

**Comment by dominh** [comment]
@taiar hmm.. looks like typical issue with assets. Unfortunately I'm unable reproduce it. Could you give me more information/details?

**Comment by everblut** [comment]
Hey @taiar the assets thing it's solved with the `rake assets` task.

It works great.

**Comment by sj26** [comment]
The comments I made on #17 apply here as well — MailCatcher is an SMTP server and deals with recipients, telling you where your program actually delivered the messages, not the mail message itself, which might have totally different addresses over many fields.

**Comment by Jeremy1026** [comment]
But mailcatcher is a development tool, that mocks an SMTP server. It’s useful to see all the information as it pertains to the tests.

**Pull request closed without merging**
