### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by marcmillien**
## Ruby version
Remove `1.9.3` from test:
- because it is no more a maintained version
- due to minimum requirement for `selenium-webdriver` 

## Tests
Sounds like tests are failing due to some race condition, so I forced the navigation after delivering mail.

## Dependencies
Finally this PR force versions for:
- `selenium-webdriver` due to the fact that phantomjs is no more supported by selenium webdriver since version `3.8` but used for the tests (it should probably be replaced by something else)
- `compass` due to the error: `NoMethodError: undefined method 'has?' for Sass::Util:Module`

### CODE REVIEW

**Comment by sj26** [comment]
Thanks!

**Comment by neumayr** [comment]
@sj26 Would you mind releasing  a version `v0.6.6` including this change (0177b45). A collegue and I, we are working on a `mailcatcher` homebrew formula and this one is currently blocking us submit the formula to homebrew. We got it working patching the files locally, but formulae should not require patches to build, as their guidelines said.

##### Our final barrier on `v.0.6.5`

```bash
NoMethodError: undefined method `has?' for Sass::Util:Module
Did you mean?  hash
               Hash
/usr/local/Cellar/mailcatcher/0.6.5/libexec/gems/compass-0.12.2/lib/compass/sass_extensions/functions/urls.rb:5:in `has?'
/usr/local/Cellar/mailcatcher/0.6.5/libexec/gems/compass-0.12.2/lib/compass/sass_extensions/functions/urls.rb:9:in `included'
[…]
```

**Comment by sj26** [comment]
Sass isn't used within the gem itself, only for compiling assets, so there's no difference within the ditributed gemball, apart from a slightly different specification object. But I'll try to get another release out soon anyway with some other improvements, too.

**Comment by sj26** [comment]
I've also emailed you an updated formula which works without requiring this change. :-)

**Pull request merged**
