### PR TITLE
Drop legacy Ruby versions, including 3.0

### LINKED ISSUE #553: 0.9.1.beta2 does not work with Ruby 3.3
```
$ mailcatcher -f -v --http-ip=0.0.0.0
Starting MailCatcher v0.9.1.beta2
==> smtp://127.0.0.1:1025
==> http://0.0.0.0:1080
```

image

Unfortunately I cannot run specs on my machine, it looks like that there are issues with `base64` (no longer a default gem) and maybe more

### PR DESCRIPTION
**Pull request by tagliala**
3.0 will EOL soon, and it has issues when compiling eventmachine

Also:

- Fix compatibility with latest Selenium
- Bump Sinatra and Rack dependency to allow Ruby 3.3

Close #553

### CODE REVIEW

**Comment by FinnIckler** [comment]
While Mailcatcher starts now, assets are not served.
```
curl localhost:1080/assets/mailcatcher.js
<html>
<body>
  <h1>No Dice</h1>
  <p>The message you were looking for does not exist, or doesn't have content of this type.</p>
</body>
</html>
```

**Comment by tagliala** [comment]
Cannot replicate on my machine 🤔

```
$ curl localhost:1080/assets/mailcatcher.js
window.Modernizr=function(e,t,r){function n(e)...
```

command line:

```
BUNDLE_GEMFILE=~/dev/mailcatcher/Gemfile bundle exec ~/dev/mailcatcher/bin/mailcatcher -f -v --http-ip=0.0.0.0
```

**Comment by FinnIckler** [comment]
Here's a repro
```
docker run -it ruby:3.3.0 /bin/bash
# installing your gem
gem install specific_install && gem specific_install -l https://github.com/tagliala/mailcatcher.git -b feature/drop-legacy-ruby-versions
mailcatcher --http-ip=0.0.0.0 --no-quit
curl localhost:1080/assets/mailcatcher.js
```

**Comment by FinnIckler** [comment]
Ok, me and a colleague figured out that this is because the coffeescript files don't get compiled when installing the gem from this repo

**Comment by tagliala** [comment]
yes, the asset compile pipeline is quite outdated :(

**Comment by sj26** [comment]
Sorry for the delay, but this is wonderful, thank you.

**Comment by ansonhoyt** [comment]
Can confirm it's working with Ruby 3.3.0 (and Rails 7.1) after `gem install mailcatcher --pre`. Happy to have this nice tool working again, just in time to develop some new emails. 😅 

Thanks all for the fix and release!

**Pull request merged**
