### PR TITLE
update CMD for Dockerfile

### PR DESCRIPTION
**Pull request by rorpage**
By combining the `ENTRYPOINT` and `CMD` I am able to get this running in a Docker container. Also, I grouped the `EXPOSE` ports together for readability.

### CODE REVIEW

**Comment by rorpage** [comment]
@sj26 It looks like my build and others are failing because of an older version of Ruby, which `selenium-webdriver` says it doesn't support any longer. Any chance we could remove it?

**Comment by sj26** [comment]
Does the current docker image not work for you?

```
$ docker run sj26/mailcatcher
Starting MailCatcher
==> smtp://0.0.0.0:1025
==> http://0.0.0.0:1080
```

**Comment by sj26** [comment]
Also, `gem install mailcatcher` should not be installing selenium, that's a dev-only dependency:

```
$ docker build .
Sending build context to Docker daemon 25.11 MB
Step 1/7 : FROM ruby:2.4
 ---> 68de654ed5ee
Step 2/7 : MAINTAINER Samuel Cochran <sj26@sj26.com>
 ---> Running in 00b0da31dc31
 ---> 01fd9d897cea
Removing intermediate container 00b0da31dc31
Step 3/7 : RUN gem install mailcatcher
 ---> Running in 1802f2c92402
Building native extensions.  This could take a while...
Successfully installed eventmachine-1.0.9.1
Successfully installed mime-types-data-3.2016.0521
Successfully installed mime-types-3.1
Successfully installed mail-2.6.6
Successfully installed rack-1.6.8
Successfully installed tilt-2.0.7
Successfully installed rack-protection-1.5.3
Successfully installed sinatra-1.4.8
Building native extensions.  This could take a while...
Successfully installed sqlite3-1.3.13
Successfully installed daemons-1.2.4
Building native extensions.  This could take a while...
Successfully installed thin-1.5.1
Successfully installed skinny-0.2.4
Successfully installed mailcatcher-0.6.5
13 gems installed
 ---> f92d6cc5c1bb
Removing intermediate container 1802f2c92402
Step 4/7 : EXPOSE 1025
 ---> Running in 387c9799668a
 ---> 1ca36241b522
Removing intermediate container 387c9799668a
Step 5/7 : EXPOSE 1080
 ---> Running in 52c8fd07114f
 ---> f82f2eb6c4eb
Removing intermediate container 52c8fd07114f
Step 6/7 : ENTRYPOINT mailcatcher -f
 ---> Running in 1d03aa53d9f2
 ---> cd73300aeed0
Removing intermediate container 1d03aa53d9f2
Step 7/7 : CMD --ip 0.0.0.0
 ---> Running in 17f5300e0244
 ---> c2a48b773a44
Removing intermediate container 17f5300e0244
Successfully built c2a48b773a44
```

**Comment by sj26** [comment]
Note that the split between CMD and ENTRYPOINT is designed so that you can `docker run mailcatcher` and it works fine, or you can override the arguments for more control like `docker run mailcatcher --ip 127.0.0.1`. Again, this seems to be working fine for me locally:

```
$ docker run mailcatcher --ip 127.0.0.1
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
```

**Comment by rorpage** [comment]
@sj26 I pulled the repo and did a `docker build -t rorpage/mailcatcher .` and then tried to run that. It acted like it didn't want to start.

The selenium dependency is loading during the Travis CI build, and it looks like my PR and others before it have been failing because `selenium-webdriver 3.4.3` requires Ruby >= 2.0.

I am 100% okay with abandoning this PR if you feel it's unwarranted. I just needed to make these changes to make it work locally. Thanks for your feedback!

**Comment by sj26** [comment]
I'm curious why it's not working for you, but afaik this is all working as intended, so I'll close this. Sounds like you've got a solve for you problem: using a forked Dockerfile. Thanks. :-)

**Pull request closed without merging**
