### PR TITLE
fixed a bug with invalid bytes in ASCII

### PR DESCRIPTION
**Pull request by elik-ru**

### CODE REVIEW

**Comment by elik-ru** [comment]
Looks like ruby 1.9.3 is not supported by selenium any more.

**Comment by BrendaEgeland** [comment]
This patch fixed the problem for me.

**Comment by sj26** [comment]
UTF-8 is not valid over the wire unless the mail server advertises 8-bit encoding, which MailCatcher does not. If you a receiving errors here then I'm afraid you or your mail library is not correctly encoding your sent email.

**Comment by elik-ru** [comment]
I'm using regular Rails 5 mailer. Of cause it's transfer encoding is  quoted-printable ascii. But inside it has one html part with utf8 encoding. What's wrong ?

**Comment by sj26** [comment]
SMTP is by default a 7-bit protocol:

https://tools.ietf.org/html/rfc821#page-3

So bodies containing bytes which require the high bit set must be encoded in some other form, usually quoted printable. The mail gem (used within rails) should probably be doing this for you transparently.

SMTP was only extended later to 8-bit by [RFC5321](https://tools.ietf.org/html/rfc5321) and then only when the server advertises a `8BITMIME` capability which MailCatcher does not.

**Comment by elik-ru** [comment]
OK, fine. I said this above - rails 5 generates a letter with quoted printable ascii encoding. Over SMTP you receive quoted printable ascii encoding.
But after decoding it you will get plain-text and html parts with utf8 encoding.
And everything works fine, but String is marked as ASCII-8BIT and JSON crashes in a try to convert it to utf8.

**Comment by sj26** [comment]
The `message["source"]` is not decoded, it should be the literal SMTP transmitted message body which should be 7-bit ascii (which is valid utf-8). If you're getting an encoding error here then the message wasn't encoded properly and isn't a clean 7-bit subset of utf-8, so forcing it to be utf-8 by replacing bad characters is going to munge the source and lie about your message over json.

**Comment by sj26** [comment]
The only decoded part is that lines with double periods would be replaced with single periods.

**Comment by sj26** [comment]
The real solve here would be to make sure that the message source when received via SMTP contains only valid 7-bit bytes and raise the error earlier with clearer instructions on how to fix it in the sender.

**Comment by sj26** [comment]
(or just rewrite the whole smtp server and build in 8bit mime support supporting first-class encodings and again raising errors earlier in the smtp exchange when invalid content is supplied.)

**Pull request closed without merging**
