### PR TITLE
support running mailcather mounted at a specific http url prefix

### PR DESCRIPTION
**Pull request by jimlar**
very useful if you want to run mailcatcher behind a shared proxy

### CODE REVIEW

**Comment by jehon** [comment]
That would be great !
Could you add a apache config example in the documentation?

**Comment by sdurrheimer** [comment]
@sj26 Hi there, do we have any chance to see this feature being merged ? It is really painful to run mailcatcher behind a proxy without this.

**Comment by sj26** [comment]
This feature doesn't currently work. I'll see if I can polish it up for release. This has been a common request, and it probably couldn't hurt.

**Comment by sdurrheimer** [comment]
@sj26 Any news ?

**Comment by sj26** [comment]
I haven't had time to fix it up yet, sorry. Feel free to take a stab if you like.

**Comment by westonganger** [comment]
+1

**Comment by sj26** [comment]
Thanks. This is supported as `--http-path` in the newest version.

**Pull request closed without merging**
